{% set version = "2.8.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sjPlot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjPlot/sjPlot_{{ version }}.tar.gz
  sha256: f8b4f6a80b920a69a4a40f8cf892e4491ec91a23d1c8f4aef2b59bb578b9691d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-bayestestr
    - r-datawizard
    - r-dplyr
    - r-effectsize
    - r-ggeffects
    - r-ggplot2 >=3.2.0
    - r-insight
    - r-knitr
    - r-parameters
    - r-performance
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.1.2
    - r-sjmisc >=2.8.2
    - r-sjstats >=0.17.8
    - r-tidyr >=1.0.0
  run:
    - r-base
    - r-mass
    - r-bayestestr
    - r-datawizard
    - r-dplyr
    - r-effectsize
    - r-ggeffects
    - r-ggplot2 >=3.2.0
    - r-insight
    - r-knitr
    - r-parameters
    - r-performance
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.1.2
    - r-sjmisc >=2.8.2
    - r-sjstats >=0.17.8
    - r-tidyr >=1.0.0

test:
  commands:
    - $R -e "library('sjPlot')"           # [not win]
    - "\"%R%\" -e \"library('sjPlot')\""  # [win]

about:
  home: https://strengejacke.github.io/sjPlot/
  license: GPL-3.0-only
  summary: Collection of plotting and table output functions for data visualization. Results of various statistical analyses (that are commonly used in social sciences) can be visualized using this package, including simple and cross tabulated frequencies, histograms, box plots, (generalized) linear models, mixed effects
    models, principal component analysis and correlation matrices, cluster analyses, scatter plots, stacked scales, effects plots of regression models (including interaction terms) and much more. This package supports labelled data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: sjPlot
# Type: Package
# Encoding: UTF-8
# Title: Data Visualization for Statistics in Social Science
# Version: 2.7.2
# Date: 2019-09-29
# Authors@R: c( person("Daniel", "Ludecke", email = "d.luedecke@uke.de", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8895-3206")), person("Alexander", "Bartel", role = "ctb", comment = c(ORCID = "0000-0002-1280-6138")), person("Carsten", "Schwemmer", email = "carsten.schwemmer@uni-bamberg.de", role = "ctb"), person(given = "Chuck", family = "Powell", role = "ctb", email = "ibecav@gmail.com", comment = c(ORCID = "0000-0002-3606-2188")) )
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Collection of plotting and table output functions for data visualization. Results of various statistical analyses (that are commonly used in social sciences) can be visualized using this package, including simple and cross tabulated frequencies, histograms, box plots, (generalized) linear models, mixed effects models, principal component analysis and correlation matrices, cluster analyses, scatter plots, stacked scales, effects plots of regression models (including interaction terms) and much more. This package supports labelled data.
# License: GPL-3
# Depends: R (>= 3.2), graphics, grDevices, stats, utils
# Imports: bayestestR (>= 0.3.0), broom, dplyr (>= 0.8.1), forcats, ggeffects (>= 0.12.0), glmmTMB, ggplot2 (>= 3.2.0), ggrepel, knitr, insight (>= 0.5.0), lme4 (>= 1.1-12), magrittr, MASS, modelr, nlme, parameters (>= 0.2.0), performance (>= 0.3.0), psych, purrr, rlang, scales, sjlabelled (>= 1.1.0), sjmisc (>= 2.8.2), sjstats (>= 0.17.5), tidyr (>= 1.0.0)
# Suggests: brms, car, cluster, cowplot, GPArotation, gridExtra, ggridges, httr, pscl, rstanarm, survey, TMB, Zelig, testthat
# URL: https://strengejacke.github.io/sjPlot/
# BugReports: https://github.com/strengejacke/sjPlot/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-29 08:01:08 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), Alexander Bartel [ctb] (<https://orcid.org/0000-0002-1280-6138>), Carsten Schwemmer [ctb], Chuck Powell [ctb] (<https://orcid.org/0000-0002-3606-2188>)
# Repository: CRAN
# Date/Publication: 2019-09-29 15:20:02 UTC
