{% set version = '2.6.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sjPlot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjPlot/sjPlot_{{ version }}.tar.gz
  sha256: 9e0db322ef8636bb118bddc28007900edeb01f844d94b812230e935f215b3775

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-broom
    - r-dplyr >=0.7.5
    - r-forcats
    - r-ggeffects >=0.7.0
    - r-ggplot2 >=2.2.1
    - r-glmmtmb
    - r-knitr
    - r-lme4 >=1.1_12
    - r-magrittr
    - r-modelr
    - r-nlme
    - r-psych
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.0.14
    - r-sjmisc >=2.7.6
    - r-sjstats >=0.17.2
    - r-tidyr >=0.7.0
  run:
    - r-base
    - r-mass
    - r-broom
    - r-dplyr >=0.7.5
    - r-forcats
    - r-ggeffects >=0.7.0
    - r-ggplot2 >=2.2.1
    - r-glmmtmb
    - r-knitr
    - r-lme4 >=1.1_12
    - r-magrittr
    - r-modelr
    - r-nlme
    - r-psych
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.0.14
    - r-sjmisc >=2.7.6
    - r-sjstats >=0.17.2
    - r-tidyr >=0.7.0

test:
  commands:
    - $R -e "library('sjPlot')"           # [not win]
    - "\"%R%\" -e \"library('sjPlot')\""  # [win]

about:
  home: https://strengejacke.github.io/sjPlot/
  license: GPL-3
  summary: Collection of plotting and table output functions for data visualization. Results
    of various statistical analyses (that are commonly used in social sciences) can
    be visualized using this package, including simple and cross tabulated frequencies,
    histograms, box plots, (generalized) linear models, mixed effects models, principal
    component analysis and correlation matrices,  cluster analyses, scatter plots, stacked
    scales, effects plots of regression  models (including interaction terms) and much
    more. This package supports labelled data.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: sjPlot
# Type: Package
# Encoding: UTF-8
# Title: Data Visualization for Statistics in Social Science
# Version: 2.6.2
# Date: 2018-12-18
# Authors@R: c( person("Daniel", "Ludecke", email = "d.luedecke@uke.de", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8895-3206")), person("Carsten", "Schwemmer", email = "carsten.schwemmer@uni-bamberg.de", role = "ctb") )
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Collection of plotting and table output functions for data visualization. Results of various statistical analyses (that are commonly used in social sciences) can be visualized using this package, including simple and cross tabulated frequencies, histograms, box plots, (generalized) linear models, mixed effects models, principal component analysis and correlation matrices,  cluster analyses, scatter plots, stacked scales, effects plots of regression  models (including interaction terms) and much more. This package supports labelled data.
# License: GPL-3
# Depends: R (>= 3.2), graphics, grDevices, stats, utils
# Imports: broom, dplyr (>= 0.7.5), forcats, ggeffects (>= 0.7.0), glmmTMB, ggplot2 (>= 2.2.1), knitr, lme4 (>= 1.1-12), magrittr, MASS, modelr, nlme, psych, purrr, rlang, scales, sjlabelled (>= 1.0.14), sjmisc (>= 2.7.6), sjstats (>= 0.17.2), tidyr (>= 0.7.0)
# Suggests: brms, car, cluster, GPArotation, gridExtra, ggrepel, ggridges, pscl, rstanarm, survey, TMB, Zelig, testthat
# URL: https://strengejacke.github.io/sjPlot/
# BugReports: https://github.com/strengejacke/sjPlot/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-12-18 16:39:15 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), Carsten Schwemmer [ctb]
# Repository: CRAN
# Date/Publication: 2018-12-18 17:10:03 UTC
