travis:
  secure:
    BINSTAR_TOKEN: umfQJQmobGEGSiB2YQA7+Ht878XW2DBsHpRYpZ1C6Zmm9re9HTZkKNvYJMPpyZzlpItjbHrS06LlYoZoJxwYDhtiGzF08NtppjrsTlI8uL2+9XdQOZRWbpBQXnh5kUOpij0o/77q7/zFISks6XEKENPdJLk8sx+FScuWpLsXu30ErD9B2et2BcL1BkDUo7gpdh0kDAwNA0WlagxEnd7s7ndkoBXuq0T9z13Hb7Ye2JskB9MmDaIf0bmqPevsA7drvqol6Gw57Yl/yZ6gBdoGeEOV8tHkyej+IYffIQSNiH6lXNjXyusI5H3M1/skRfJ9rzBSMQ0IvMC5wMwKAtrShwE8DlWXgQ3uG0p2bTQa0R0cV6FMoqWZAzc+aUkKim/76KKAsOMxiJWoKHTk0f/0ZdJ3O9K+adZ4He/H26rwSBzbJOTKyiCzPbMyauHFVaoFPhurIQuReFL93GaDSElfV7ELMS+4qYalz2ZQlorMaToTlDDKifHbcq/SFaNlTAdEFZdJD8PuSIEOjQe6O4r64F6j9RwbYYh+B3UuXIOIWHv/uEF8VnkqZDUU+YOd7r/01PrX/RVIWmmD99pMjdycQgDZ548vmmu164Y2hbVL44AWLtBw22844OUxSmMmc4SCKDcHAzLj95zs11V8lr3p9IR6pH5wMAW+zMQPGf85Cw0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
